In [1]:
from sys import path
from os.path import realpath
path.append(realpath("../")) # Makes it works everywhere
from PIL import Image
import numpy as np

In [75]:
path = 'imgs/linea.png'
image = Image.open(path).convert('L')
image = np.asarray(image)
shape = np.shape(image)
padded_image = np.pad(image)

encoded_b2 = ""
for i in padded_image:
    for j, el in enumerate(i):
        encoded_b2 += format(el, '08b')

encoded_b2 = '\n'.join(encoded_b2[i:i+8] for i in range(0, len(encoded_b2), 8))

In [76]:
with open('VHDL/images_in_fpga/src/linea.mif', 'w')  as outfile:   
    outfile.write(encoded_b2)

Falta la vuelta (txt2png)

In [11]:
shape = (6,6)

img_mat = np.uint8(np.zeros(shape=shape))

img_file = open('VHDL/images_in_fpga/test_img.txt', 'r')

for i in range(shape[0]):
    for j in range(shape[1]):
        line = img_file.readline()
        if not line:
            break
        img_mat[i][j] = int(line.strip(), 2)

print(img_mat)

[[  0   0   0   0   0   0]
 [  0  15 224   3 170   0]
 [  0  51 204 238   0   0]
 [  0  15 240 195   4   0]
 [  0 248 136 120 138   0]
 [  0   0   0   0   0   0]]
